### ISSUE TITLE
Handling input files in the epJSON format

### ISSUE THREAD

**Issue by lymereJ** [jamiebull1/geomeppy#201]
AFAIK `geomeppy` doesn't handle files in the `epjson` format, the `idf` file format has not yet been depreciated but might in the future. Should `geomeppy` be able to handle `epjson` files?

**Comment by jamiebull1** [comment]
That's an issue for `eppy`, and I think @santoshphilip has it in hand, or at least has a plan in place.

**Comment by santoshphilip** [comment]
Wow ! @jamiebull1 is alive and well.

@lymereJ , It is implemented in `eppy3000`. <https://github.com/pyenergyplus/eppy3000>
`eppy3000` will read both IDF and epJSON file and will convert between them.
You can also run `eppy` from `eppy3000`

For conversion see these pages
https://eppy3000.readthedocs.io/en/latest/tutorial1.html#Convert-to-epJSON-with-eppy
https://eppy3000.readthedocs.io/en/latest/tutorial1.html#Convert-to-epJSON-without-eppy

General documentation is in
https://eppy3000.readthedocs.io/en/latest/index.html

The code is in flux at the moment, since there is active work on it at the moment.
Although I don't think the conversion code will change.

**Comment by lymereJ** [comment]
Thanks! I'll look into `eppy3000`.
